### ISSUE TITLE
Directory marker

### ISSUE THREAD

**Issue by aldof19** [rcamuccio/pipeline-tutorials#1]
In the data reduction tutorial, after the first dark-flat reduction, the command os.chdir does not work because the tutorial is still in the dark-flat directory

A simple fix would be to add os.chdir("../../../..") to reset back to home directory. Careful with the last one

**Comment by rcamuccio** [comment]
Thanks for pointing that out to me. Serves me right for changing to relative paths without considering the change of directory reset. I had originally gone the route of just writing in the absolute paths, so I reverted back to that. I know it's a bit clunky of a solution, but it's a quick fix for now while I build the rest of the tutorials.
